export enum FieldTypes {
    CheckboxField,
    DateField,
    DateTimeField,
    DecimalField,
    DoubleField,
    EmailField,
    GeographyField,
    HiddenField,
    IntField,
    LimitedStringField,
    PasswordField,
    RecurringExpressionField,
    SelectField,
    StringField,
    TimeField,
}
