/**
 * Skysmack API
 * Official API documentation for Skysmack
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hej@itinstituttet.dk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FieldValidator } from './field-validatior';
import { FieldAccessPermission } from './field-access-permission';

export interface FieldSchemaViewModel {
    key: string;
    type: string;
    order?: number;
    validators?: Array<FieldValidator>;
    display?: string;
    readPermission?: FieldAccessPermission;
    writePermission?: FieldAccessPermission;
}
