export const callDataValue = [
    'historyid',
    'callid',
    'duration',
    'time-start',
    'time-answered',
    'time-end',
    'reason-terminated',
    'from-no',
    'to-no',
    'from-dn',
    'to-dn',
    'dial-no',
    'reason-changed',
    'final-number',
    'final-dn',
    'bill-code',
    'bill-rate',
    'bill-cost',
    'bill-name',
    'from-type',
    'to-type',
    'final-type',
    'from-dispname',
    'to-dispname',
    'final-dispname'
];

export const callDataDisplay = [
    'History ID',
    'Call ID',
    'Duration',
    'Time start',
    'Time answered',
    'Time end',
    'Reason terminated',
    'From no',
    'To no',
    'From dn',
    'To dn',
    'Dial no',
    'Reason changed',
    'Final number',
    'Final dn',
    'Bill code',
    'Bill rate',
    'Bill cost',
    'Bill name',
    'From type',
    'To type',
    'Final type',
    'From display name',
    'To display name',
    'Final display name'
]