// export * from './lodgings/ng-lodgings.module';
// export * from './lodging-reservations/ng-lodging-reservations.module';
// export * from './identities/ng-identities.module';
// export * from './maintenance/ng-assignments.module';
// export * from './oauth2/ng-oauth2.module';
// export * from './persons/ng-persons.module';
// export * from './invoices/ng-invoices.module';
// export * from './persons-lodging-reservations/ng-persons-lodging-reservations.module';
// export * from './products/ng-products.module';
// export * from './products-pricings/ng-products-pricings.module';
// // export * from './skysmack-core/index';
// export * from './terminal-payments/ng-terminal-payments.module';
// export * from './products-pricings/ng-products-pricings.module';
export * from './lodgings/index';
export * from './lodging-reservations/index';
export * from './identities/index';
export * from './maintenance/index';
export * from './oauth2/index';
export * from './persons/index';
export * from './invoices/index';
export * from './persons-lodging-reservations/index';
export * from './products/index';
export * from './products-pricings/index';
// export * from './skysmack-core/index';
export * from './terminal-payments/index';
export * from './products-pricings/index';
export * from './account/index';
